#Comment: PC Character
#Describes The basic stats of this character
---
name: The Big Guy 
description: It's the Big Guy!
is_pc: False
is_ally: False # Unclear when this would come up
pronouns: he/him/his
greeting: "BANELY: YEEEESSSHHH"
hp: 7
size: 3 # Working on this bit
weapons: 
  - name: big fists
    type: melee
    dice: 1d6
    category: unarmed
morale: 
  8
armour:
  type: leather
  dice: 1d2
silver: 1
