#Comment: PC Character
#Describes The basic stats of this character
---
name: Rolf 
description: It's Rolf! Keep Rolfing Rolfing Rolfing Rolfing
is_pc: True
is_ally: True # Unclear when this would come up
greeting: Rarg, I'm a scary guy, watch out for me!!! OOOOooohhh I'm Rolf, by the way
hp: 3
abilities: 
  strength: -2
  presence: 1 
  agility: 1 
  toughness: 1
items: 
  - type: potion
    heal: 1
weapons: 
  - name: big sword 2
    type: melee
    dice: 1d6
    dr: 12
    category: sword
    rank: primary
  - name: big sword
    type: melee
    dice: 1d6
    dr: 12
    category: sword
  - name: big sword 3
    type: melee
    dice: 1d6
    dr: 12
    category: sword
morale: 
  null
armour:
  type: leather
  dice: 1d2
silver: 1
