#Comment: PC Character
#Describes The basic stats of this character
---
name: Urvarg 
description: It's Urvarg, baby!
is_pc: True
is_ally: True # Unclear when this would come up
pronouns: he/him/his
greeting: Rarg, I'm a scary guy, watch out for me!!! OOOOooohhh
hp: 5 # originally 26, bit high
abilities: 
  strength: 2
  presence: 1 
  agility: 1 
  toughness: 1
items: 
  - type: healing
    name: medicine chest
    dice: 1d6
    number: 4 # this should be something that's rolled sometimes
weapons: 
  - name: big sword 4
    type: melee
    dice: 1d4
    dr: 12
    category: sword
morale: 
  null
armour:
  type: leather
  dice: 1d4
silver: 1
