#Comment: PC Character
#Describes The basic stats of this character
---
name: Urm
description: Oh no, it's Urm
is_pc: True
is_ally: True # Unclear when this would come up
pronouns: he/him/his
greeting: Awh jeez, what the heck
hp: 3
abilities: 
  strength: 0
  presence: 4 
  agility: 0 
  toughness: 0
items: 
  - type: healing
    name: medicine chest
    dice: 1d6
    number: 4 # this should be something that's rolled sometimes
  - type: scroll
    name: fire ball
    flavour_name: Palms open the southern gate
  - type: scroll
    name: lightning bolt
    flavour_name: Nine violet signs unknot the storm
  - type: scroll
    name: death
    flavour_name: DEATH!
  - type: scroll
    name: grace
    flavour_name: Grace of a dead saint
weapons: 
  - name: knife
    type: melee
    dice: 1d4
    dr: 12
    category: knife
morale: 
  null
armour:
  type: leather
  dice: 1d4
silver: 1
